### ISSUE TITLE
Is the guide still being written ?

### ISSUE THREAD

**Issue by IrfanKhan66** [Ciarands/web-reversing#1]
this is not an issue but a question
**Q: is the repo active/are you going to upload the rest of the guides.md ?**
if yes then can you tell how much time would it take ?

**Comment by Ciarands** [comment]
Yeah, I really do want to focus on things like this, I have a fair portion written along with a few challenges for this guide, although I've been so busy with other work I've had little chance to work on this sadly.
As soon as life calms down a bit I want to focus on writing a decent comprehensive guide for the topic.
Sorry for having this for so long and not adding to it, but obviously paid work takes priority.
